homeassistant:
  # Name of the location where Home Assistant is running
  name: Borthwick Manor
  # Location required to calculate the time the sun rises and sets
  latitude: 45.565257
  longitude: -122.673608
  # Impacts weather/sunrise data
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor weather:
  platform: yr
  monitored_conditions:
    - temperature
    - precipitation
    - windSpeed

sensor bedroom_temperature:
  platform: rest
  resource: http://sleepsoundsbot.local:6125/temperature
  value_template: '{{ value_json.degrees_f }}'
  method: GET
  name: Bedroom Temperature
  unit_of_measurement: "°F"

sensor bedroom_light:
  platform: rest
  resource: http://sleepsoundsbot.local:6125/light
  value_template: '{{ value_json.percent }}'
  method: GET
  name: Bedroom Lighting
  unit_of_measurement: "% Brightness"

sensor bedroom_humidity:
  platform: rest
  resource: http://sleepsoundsbot.local:6125/humidity
  value_template: '{{ value_json.percent }}'
  name: Bedroom Humidity
  unit_of_measurement: "% Humidity"

sensor ip:
  platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

switch cmdline:
  platform: command_line
  switches:
    svxlink:
      oncmd: sudo service svxlink start
      offcmd: sudo service svxlink stop
      statecmd: status svxlink | grep -q "start"
    dstarrepeaterd:
      oncmd: sudo service dstarrepeaterd start
      offcmd: sudo service dstarrepeaterd stop
      statecmd: status dstarrepeaterd | grep -q "start"

switch wol_carmack:
  platform: wake_on_lan
  mac_address: "98:90:96:A8:C6:B7"
  name: "Wake Carmack"
  host: "10.224.224.22"

media_player sleepsoundsbot:
  platform: mpd
  server: sleepsoundsbot.local
  location: Adam & TJ's Bedroom

notify twoline:
  name: Twoline
  platform: twoline
  resource: http://127.0.0.1:6224/message/hass/
  color:
    red: 0
    green: 255
    blue: 255

automation:
  - alias: Stop Echolink
    trigger:
      platform: event
      event_type: keyboard_command
      event_data:
        message: "stop echolink"
    action:
      - service: notify.twoline
        data:
          message: "Stopping Echolink"
      - service: switch.turn_off
        entity_id: switch.svxlink
  - alias: Start Echolink
    trigger:
      platform: event
      event_type: keyboard_command
      event_data:
        message: "start echolink"
    action:
      - service: notify.twoline
        data:
          message: "Starting Echolink"
      - service: switch.turn_on
        entity_id: switch.svxlink
  - alias: Stop D-Star Repeater
    trigger:
      platform: event
      event_type: keyboard_command
      event_data:
        message: "stop dstar"
    action:
      - service: notify.twoline
        data:
          message: "Stopping D-Star Repeater"
      - service: switch.turn_off
        entity_id: switch.dstarrepeaterd
  - alias: Start D-Star Repeater
    trigger:
      platform: event
      event_type: keyboard_command
      event_data:
        message: "start dstar"
    action:
      - service: notify.twoline
        data:
          message: "Starting D-Star Repeater"
      - service: switch.turn_on
        entity_id: switch.dstarrepeaterd
