homeassistant:
  # Name of the location where Home Assistant is running
  name: Borthwick Manor
  # Location required to calculate the time the sun rises and sets
  latitude: 45.565257
  longitude: -122.673608
  # Impacts weather/sunrise data
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor weather:
  platform: yr
  monitored_conditions:
    - temperature
    - precipitation
    - windSpeed

switch cmdline:
  platform: command_line
  switches:
    SVXLink Repeater:
      oncmd: sudo service svxlink start
      offcmd: sudo service svxlink stop
      statecmd: status svxlink | grep -q "start"

switch wol_carmack:
  platform: wake_on_lan
  mac_address: "98:90:96:A8:C6:B7"
  name: "Wake Carmack"
  host: "10.224.224.22"

media_player sleepsoundsbot:
  platform: mpd
  server: sleepsoundsbot.local
  location: Adam & TJ's Bedroom

#notify twoline:
#  name: Twoline
#  platform: rest
#  resource: http://127.0.0.1:6224/message/hass/
#  method: POST_JSON

